export const SERVICES = [
  {
    id: "meta-ads",
    slug: "meta-ads",
    num: "01",
    nameKey: "svc.meta.name",
    descKey: "svc.meta.desc",
    longKey: "svc.meta.long",
    priceKey: "svc.meta.price",
    features: ["svc.meta.f1", "svc.meta.f2", "svc.meta.f3", "svc.meta.f4", "svc.meta.f5"],
    cta: "start" as const,
    note: "ad" as const,
    icon: "megaphone" as const,
  },
  {
    id: "web-development",
    slug: "web-development",
    num: "02",
    nameKey: "svc.web.name",
    descKey: "svc.web.desc",
    longKey: "svc.web.long",
    priceKey: "svc.web.price",
    features: ["svc.web.f1", "svc.web.f2", "svc.web.f3", "svc.web.f4", "svc.web.f5"],
    cta: "start" as const,
    note: "host" as const,
    icon: "monitor" as const,
  },
  {
    id: "social-media",
    slug: "social-media",
    num: "03",
    nameKey: "svc.social.name",
    descKey: "svc.social.desc",
    longKey: "svc.social.long",
    priceKey: "svc.social.price",
    features: ["svc.social.f1", "svc.social.f2", "svc.social.f3", "svc.social.f4", "svc.social.f5"],
    cta: "start" as const,
    note: null,
    icon: "share" as const,
  },
  {
    id: "seo",
    slug: "seo",
    num: "04",
    nameKey: "svc.seo.name",
    descKey: "svc.seo.desc",
    longKey: "svc.seo.long",
    priceKey: "svc.seo.price",
    features: ["svc.seo.f1", "svc.seo.f2", "svc.seo.f3", "svc.seo.f4", "svc.seo.f5"],
    cta: "start" as const,
    note: null,
    icon: "search" as const,
  },
  {
    id: "brand-identity",
    slug: "brand-identity",
    num: "05",
    nameKey: "svc.brand.name",
    descKey: "svc.brand.desc",
    longKey: "svc.brand.long",
    priceKey: "svc.brand.price",
    features: ["svc.brand.f1", "svc.brand.f2", "svc.brand.f3", "svc.brand.f4", "svc.brand.f5"],
    cta: "start" as const,
    note: null,
    icon: "palette" as const,
  },
  {
    id: "consultancy",
    slug: "consultancy",
    num: "06",
    nameKey: "svc.consult.name",
    descKey: "svc.consult.desc",
    longKey: "svc.consult.long",
    priceKey: "svc.consult.price",
    features: ["svc.consult.f1", "svc.consult.f2", "svc.consult.f3", "svc.consult.f4", "svc.consult.f5"],
    cta: "book" as const,
    note: null,
    icon: "compass" as const,
  },
  {
    id: "video",
    slug: "video",
    num: "07",
    nameKey: "svc.video.name",
    descKey: "svc.video.desc",
    longKey: "svc.video.long",
    priceKey: "svc.video.price",
    features: ["svc.video.f1", "svc.video.f2", "svc.video.f3", "svc.video.f4", "svc.video.f5"],
    cta: "start" as const,
    note: null,
    icon: "video" as const,
  },
] as const;

export type ServiceSlug = (typeof SERVICES)[number]["slug"];

export const TEAM = [
  {
    id: "meerak",
    name: "Meerak Baloch",
    photo: "/team/meerak.jpg",
    roleKey: "team.meerak.role",
    bioKey: "team.meerak.bio",
  },
  {
    id: "soaima",
    name: "Soaima Tahir",
    photo: "/team/soaima.jpg?v=5",
    roleKey: "team.soaima.role",
    bioKey: "team.soaima.bio",
  },
  {
    id: "muzammil",
    name: "Muzammil Mehmood",
    photo: "/team/muzammil.jpg",
    roleKey: "team.muzammil.role",
    bioKey: "team.muzammil.bio",
  },
  {
    id: "tahir",
    name: "Tahir Majeed",
    photo: "/team/tahir.jpg",
    roleKey: "team.tahir.role",
    bioKey: "team.tahir.bio",
  },
  {
    id: "muqaddas",
    name: "Muqaddas Saba",
    photo: "/team/muqaddas.jpg",
    roleKey: "team.muqaddas.role",
    bioKey: "team.muqaddas.bio",
  },
  {
    id: "shahzor",
    name: "Shahzor Ahmed",
    photo: "/team/shahzor.jpg",
    roleKey: "team.shahzor.role",
    bioKey: "team.shahzor.bio",
  },
] as const;

export const VIDEO_PACKAGES = [
  {
    id: "speed",
    num: "01",
    name: { en: "Speed Ramp", ur: "سپیڈ ریمپ" },
    popular: false,
    reel: "PKR 1,999",
    month: "PKR 17,999",
    cadence: { en: "4 reels / week · 30–40 sec", ur: "4 ریلز / ہفتہ · 30–40 سیکنڈ" },
    features: {
      en: ["Shooting", "Editing", "Final delivery"],
      ur: ["شوٹنگ", "ایڈیٹنگ", "حتمی ڈیلیوری"],
    },
  },
  {
    id: "production",
    num: "02",
    name: { en: "Production", ur: "پروڈکشن" },
    popular: false,
    reel: "PKR 3,999",
    month: "PKR 29,999",
    cadence: { en: "2 reels / week · 60–90 sec", ur: "2 ریلز / ہفتہ · 60–90 سیکنڈ" },
    features: {
      en: ["Scripting", "Professional shooting", "Professional mic", "Lighting", "Editing", "Final delivery"],
      ur: ["اسکرپٹ", "پروفیشنل شوٹنگ", "پروفیشنل مائیک", "لائٹنگ", "ایڈیٹنگ", "حتمی ڈیلیوری"],
    },
  },
  {
    id: "cinema",
    num: "03",
    name: { en: "Cinematography", ur: "سینیماٹوگرافی" },
    popular: false,
    reel: "PKR 5,999",
    month: "PKR 45,999",
    cadence: { en: "2 reels / week · 60–90 sec", ur: "2 ریلز / ہفتہ · 60–90 سیکنڈ" },
    features: {
      en: [
        "Scripting",
        "Professional shooting",
        "Professional mic",
        "Lighting",
        "Cinematic editing",
        "Final delivery",
      ],
      ur: ["اسکرپٹ", "پروفیشنل شوٹنگ", "پروفیشنل مائیک", "لائٹنگ", "سینیماٹک ایڈیٹنگ", "حتمی ڈیلیوری"],
    },
  },
  {
    id: "mix",
    num: "04",
    name: { en: "Growth Mix", ur: "گروتھ مکس" },
    popular: true,
    reel: null,
    month: "PKR 43,999",
    cadence: { en: "16 reels / month", ur: "16 ریلز / ماہ" },
    features: {
      en: [
        "2× Speed Ramp reels / week, 30–40 sec, shooting + editing + delivery",
        "1× Production reel / week, 60–90 sec, scripting + shooting + mic + lighting + editing",
        "1× Cinematography reel / week, 60–90 sec, scripting + shooting + mic + lighting + cinematic edit",
        "Monthly output: 8 Speed Ramp + 4 Production + 4 Cinematography reels",
      ],
      ur: [
        "ہفتے میں 2 سپیڈ ریمپ ریلز, 30–40 سیکنڈ، شوٹنگ + ایڈیٹنگ + ڈیلیوری",
        "ہفتے میں 1 پروڈکشن ریل, 60–90 سیکنڈ، اسکرپٹ + شوٹنگ + مائیک + لائٹنگ + ایڈیٹنگ",
        "ہفتے میں 1 سینیماٹوگرافی ریل, 60–90 سیکنڈ، اسکرپٹ + شوٹنگ + مائیک + لائٹنگ + سینیماٹک ایڈٹ",
        "ماہانہ آؤٹ پٹ: 8 سپیڈ ریمپ + 4 پروڈکشن + 4 سینیماٹوگرافی ریلز",
      ],
    },
  },
] as const;

export const WEB_PACKAGES = [
  {
    id: "basic",
    num: "01",
    nameKey: "pricing.web.basic",
    price: "PKR 30,000",
    popular: false,
    bestFor: {
      en: "Best for: small / new business",
      ur: "بہترین: چھوٹے / نئے کاروبار کے لیے",
    },
    features: {
      en: [
        "WooCommerce / Shopify",
        "Up to 30 products",
        "5 key pages",
        "COD + basic payment setup",
        "WhatsApp + shipping setup",
        "Mobile responsive + basic SEO",
        "GA4 + Meta Pixel",
        "14-day support",
      ],
      ur: [
        "WooCommerce / Shopify",
        "30 پروڈکٹس تک",
        "5 اہم صفحات",
        "COD + بنیادی ادائیگی",
        "واٹس ایپ + شپنگ سیٹ اپ",
        "موبائل ریسپانسیو + بنیادی SEO",
        "GA4 + Meta Pixel",
        "14 دن سپورٹ",
      ],
    },
  },
  {
    id: "growth",
    num: "02",
    nameKey: "pricing.web.growth",
    price: "PKR 45,000",
    popular: true,
    bestFor: {
      en: "Best for: business ready to grow",
      ur: "بہترین: ترقی کے لیے تیار کاروبار",
    },
    features: {
      en: [
        "Everything in Basic",
        "Up to 100 products",
        "8 pages",
        "Conversion-focused UX",
        "Payment + courier integration",
        "Speed optimization",
        "Product upload assistance",
        "30-day support",
      ],
      ur: [
        "بیسک کی ساری چیزیں",
        "100 پروڈکٹس تک",
        "8 صفحات",
        "کنورژن فوکسڈ UX",
        "ادائیگی + کورئیر انٹیگریشن",
        "اسپیڈ آپٹمائزیشن",
        "پروڈکٹ اپلوڈ میں مدد",
        "30 دن سپورٹ",
      ],
    },
  },
  {
    id: "premium",
    num: "03",
    nameKey: "pricing.web.premium",
    price: "PKR 65,000",
    popular: false,
    bestFor: {
      en: "Best for: established business",
      ur: "بہترین: قائم شدہ کاروبار کے لیے",
    },
    features: {
      en: [
        "Everything in Growth",
        "Up to 300 products",
        "12 pages",
        "Custom UI/UX",
        "Advanced filters/search",
        "Custom integrations",
        "Advanced tracking + optimization",
        "60-day support",
      ],
      ur: [
        "گروتھ کی ساری چیزیں",
        "300 پروڈکٹس تک",
        "12 صفحات",
        "کسٹم UI/UX",
        "ایڈوانس فلٹرز / سرچ",
        "کسٹم انٹیگریشنز",
        "ایڈوانس ٹریکنگ + آپٹمائزیشن",
        "60 دن سپورٹ",
      ],
    },
  },
] as const;

export const META_PACKAGES = [
  {
    id: "basic",
    num: "01",
    nameKey: "pricing.web.basic" as const,
    price: "PKR 10,000 / month",
    popular: false,
    bestFor: {
      en: "Best for: testing paid ads",
      ur: "بہترین: پیڈ اشتہارات ٹیسٹ کرنے کے لیے",
    },
    features: {
      en: [
        "Business Manager setup",
        "Pixel setup",
        "Up to 2 campaigns",
        "Audience research",
        "Prospecting",
        "Basic retargeting",
        "Monthly optimization",
        "Monthly report",
      ],
      ur: [
        "بزنس منیجر سیٹ اپ",
        "پکسل سیٹ اپ",
        "2 کیمپینز تک",
        "سامعین ریسرچ",
        "پراسپیکٹنگ",
        "بنیادی ری ٹارگٹنگ",
        "ماہانہ آپٹمائزیشن",
        "ماہانہ رپورٹ",
      ],
    },
  },
  {
    id: "growth",
    num: "02",
    nameKey: "pricing.web.growth" as const,
    price: "PKR 15,000 / month",
    popular: true,
    bestFor: {
      en: "Best for: consistent orders / leads",
      ur: "بہترین: مسلسل آرڈرز / لیڈز",
    },
    features: {
      en: [
        "Everything in Basic",
        "Up to 4 campaigns",
        "Prospecting + retargeting",
        "Audience testing",
        "Creative testing",
        "Conversion tracking",
        "Bi-weekly optimization",
        "Monthly strategy report",
      ],
      ur: [
        "بیسک کی ساری چیزیں",
        "4 کیمپینز تک",
        "پراسپیکٹنگ + ری ٹارگٹنگ",
        "سامعین ٹیسٹنگ",
        "کریئیٹو ٹیسٹنگ",
        "کنورژن ٹریکنگ",
        "دو ہفتے کی آپٹمائزیشن",
        "ماہانہ سٹریٹجی رپورٹ",
      ],
    },
  },
  {
    id: "premium",
    num: "03",
    nameKey: "pricing.web.premium" as const,
    price: "PKR 20,000 / month",
    popular: false,
    bestFor: {
      en: "Best for: higher-spend advertisers",
      ur: "بہترین: زیادہ اشتہاری خرچ والے",
    },
    features: {
      en: [
        "Everything in Growth",
        "Up to 6 campaigns",
        "Advanced retargeting",
        "Custom / lookalike audiences",
        "Scaling strategy",
        "A/B testing",
        "Weekly optimization",
        "Weekly monitoring",
      ],
      ur: [
        "گروتھ کی ساری چیزیں",
        "6 کیمپینز تک",
        "ایڈوانس ری ٹارگٹنگ",
        "کسٹم / لُک الاک سامعین",
        "اسکیلنگ سٹریٹجی",
        "A/B ٹیسٹنگ",
        "ہفتہ وار آپٹمائزیشن",
        "ہفتہ وار مانیٹرنگ",
      ],
    },
  },
] as const;

export const SOCIAL_PACKAGES = [
  {
    id: "basic",
    num: "01",
    nameKey: "pricing.web.basic" as const,
    price: "PKR 15,000 / month",
    popular: false,
    bestFor: {
      en: "Best for: consistent presence",
      ur: "بہترین: باقاعدہ موجودگی",
    },
    features: {
      en: [
        "4 Reels",
        "8 graphics",
        "Content calendar",
        "Captions + copywriting",
        "Posting / scheduling",
        "Story content",
        "Basic comment management",
      ],
      ur: [
        "4 ریلز",
        "8 گرافکس",
        "کنٹینٹ کیلنڈر",
        "کیپشنز + کاپی رائٹنگ",
        "پوسٹنگ / شیڈولنگ",
        "اسٹوری کنٹینٹ",
        "بنیادی کمنٹس مینجمنٹ",
      ],
    },
  },
  {
    id: "growth",
    num: "02",
    nameKey: "pricing.web.growth" as const,
    price: "PKR 25,000 / month",
    popular: true,
    bestFor: {
      en: "Best for: consistent growth",
      ur: "بہترین: مسلسل ترقی",
    },
    features: {
      en: [
        "8 Reels",
        "12 graphics",
        "Content strategy",
        "Captions + copywriting",
        "Posting / scheduling",
        "Story content",
        "Comment management",
        "Monthly report",
      ],
      ur: [
        "8 ریلز",
        "12 گرافکس",
        "کنٹینٹ سٹریٹجی",
        "کیپشنز + کاپی رائٹنگ",
        "پوسٹنگ / شیڈولنگ",
        "اسٹوری کنٹینٹ",
        "کمنٹس مینجمنٹ",
        "ماہانہ رپورٹ",
      ],
    },
  },
  {
    id: "premium",
    num: "03",
    nameKey: "pricing.web.premium" as const,
    price: "PKR 40,000 / month",
    popular: false,
    bestFor: {
      en: "Best for: strong brand presence",
      ur: "بہترین: مضبوط برانڈ موجودگی",
    },
    features: {
      en: [
        "12 Reels",
        "18 graphics",
        "Advanced content strategy",
        "Promotional creatives",
        "Copywriting",
        "Posting / scheduling",
        "Story content",
        "Comments + basic DMs",
        "Monthly analytics",
      ],
      ur: [
        "12 ریلز",
        "18 گرافکس",
        "ایڈوانس کنٹینٹ سٹریٹجی",
        "پروموشنل کریئیٹوز",
        "کاپی رائٹنگ",
        "پوسٹنگ / شیڈولنگ",
        "اسٹوری کنٹینٹ",
        "کمنٹس + بنیادی DMs",
        "ماہانہ اینالیٹکس",
      ],
    },
  },
] as const;

export const INDUSTRIES = [
  { key: "ind.retail", icon: "shopping" as const },
  { key: "ind.food", icon: "utensils" as const },
  { key: "ind.estate", icon: "building" as const },
  { key: "ind.health", icon: "heart" as const },
  { key: "ind.edu", icon: "graduation" as const },
  { key: "ind.pro", icon: "briefcase" as const },
  { key: "ind.local", icon: "map" as const },
  { key: "ind.startups", icon: "rocket" as const },
] as const;

export const WORK_ITEMS = [
  { id: "c1", titleKey: "work.c1", bodyKey: "work.c1b", kind: "web" as const },
  { id: "c2", titleKey: "work.c2", bodyKey: "work.c2b", kind: "land" as const },
  { id: "c3", titleKey: "work.c3", bodyKey: "work.c3b", kind: "social" as const },
  { id: "c4", titleKey: "work.c4", bodyKey: "work.c4b", kind: "brand" as const },
  { id: "c5", titleKey: "work.c5", bodyKey: "work.c5b", kind: "ads" as const },
] as const;

export const FAQ_IDS = ["1", "2", "3", "4", "5", "6", "7", "8", "9"] as const;

export const PROCESS_STEPS = [
  { num: "01", titleKey: "process.1", bodyKey: "process.1b" },
  { num: "02", titleKey: "process.2", bodyKey: "process.2b" },
  { num: "03", titleKey: "process.3", bodyKey: "process.3b" },
  { num: "04", titleKey: "process.4", bodyKey: "process.4b" },
] as const;

export const WHY = [
  { titleKey: "why.s1", bodyKey: "why.s1b" },
  { titleKey: "why.s2", bodyKey: "why.s2b" },
  { titleKey: "why.s3", bodyKey: "why.s3b" },
  { titleKey: "why.s4", bodyKey: "why.s4b" },
  { titleKey: "why.s5", bodyKey: "why.s5b" },
] as const;
